import ExcelJS from "exceljs";
import type { CompanyBrand, ReportMeta } from "@/lib/reports/types";

export async function createBrandedWorkbook(opts: {
  brand: CompanyBrand;
  meta: ReportMeta;
  sheetName: string;
  columns: { header: string; key: string; width?: number }[];
  rows: Record<string, string | number | null | undefined>[];
}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = opts.brand.name;
  wb.created = new Date();

  const sheet = wb.addWorksheet(opts.sheetName, {
    views: [{ rightToLeft: true }],
  });

  sheet.mergeCells("A1:G1");
  sheet.getCell("A1").value = opts.brand.name;
  sheet.getCell("A1").font = { bold: true, size: 16, color: { argb: "FF2A5A8F" } };

  sheet.mergeCells("A2:G2");
  sheet.getCell("A2").value = [
    opts.brand.address,
    opts.brand.phone,
    opts.brand.email,
  ]
    .filter(Boolean)
    .join(" · ");

  sheet.mergeCells("A3:G3");
  sheet.getCell("A3").value = opts.meta.title;
  sheet.getCell("A3").font = { bold: true, size: 13 };

  sheet.mergeCells("A4:G4");
  sheet.getCell("A4").value =
    `No: ${opts.meta.reportNumber} | Date: ${opts.meta.reportDate} | By: ${opts.meta.generatedBy} | At: ${opts.meta.generatedAt}` +
    (opts.meta.from && opts.meta.to
      ? ` | Period: ${opts.meta.from} → ${opts.meta.to}`
      : "");

  sheet.addRow([]);

  const headerRow = sheet.addRow(opts.columns.map((c) => c.header));
  headerRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF2A5A8F" },
    };
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
  });

  opts.columns.forEach((c, i) => {
    sheet.getColumn(i + 1).width = c.width || 16;
  });

  for (const row of opts.rows) {
    sheet.addRow(opts.columns.map((c) => row[c.key] ?? ""));
  }

  sheet.addRow([]);
  sheet.addRow([`Generated by Media Office — ${opts.brand.name}`]);

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
