import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { CompanyBrand, ReportMeta } from "@/lib/reports/types";
import { BRAND_HEX } from "@/lib/reports/types";

type AutoTableDoc = jsPDF & {
  lastAutoTable?: { finalY: number };
};

async function fetchImageDataUrl(url: string | null | undefined) {
  if (!url) return null;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const buf = Buffer.from(await res.arrayBuffer());
    const ct = res.headers.get("content-type") || "image/png";
    return `data:${ct};base64,${buf.toString("base64")}`;
  } catch {
    return null;
  }
}

export async function createBrandedPdf(opts: {
  brand: CompanyBrand;
  meta: ReportMeta;
  orientation?: "portrait" | "landscape";
}) {
  const doc = new jsPDF({
    orientation: opts.orientation || "portrait",
    unit: "pt",
    format: "a4",
  }) as AutoTableDoc;

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const logo = await fetchImageDataUrl(opts.brand.logo_url);

  const drawHeader = () => {
    doc.setFillColor(42, 90, 143);
    doc.rect(0, 0, pageW, 72, "F");
    if (logo) {
      try {
        doc.addImage(logo, "PNG", 36, 14, 44, 44);
      } catch {
        // ignore bad logo
      }
    }
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text(opts.brand.name || "Media Office", logo ? 92 : 36, 32);
    doc.setFontSize(9);
    const contact = [
      opts.brand.address,
      opts.brand.phone,
      opts.brand.email,
    ]
      .filter(Boolean)
      .join("  ·  ");
    if (contact) doc.text(contact, logo ? 92 : 36, 50);

    doc.setTextColor(30, 40, 55);
    doc.setFontSize(14);
    doc.text(opts.meta.title, 36, 100);
    doc.setFontSize(9);
    doc.setTextColor(90, 100, 115);
    doc.text(`Report No: ${opts.meta.reportNumber}`, 36, 116);
    doc.text(`Date: ${opts.meta.reportDate}`, 36, 128);
    doc.text(`Generated by: ${opts.meta.generatedBy}`, 36, 140);
    doc.text(`Generated at: ${opts.meta.generatedAt}`, 36, 152);
    if (opts.meta.from && opts.meta.to) {
      doc.text(`Period: ${opts.meta.from} → ${opts.meta.to}`, 36, 164);
    }
  };

  const drawFooter = () => {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      if (opts.brand.report_watermark) {
        doc.setTextColor(230, 235, 240);
        doc.setFontSize(48);
        doc.text(opts.brand.report_watermark, pageW / 2, pageH / 2, {
          align: "center",
          angle: 35,
        });
      }
      doc.setDrawColor(42, 90, 143);
      doc.setLineWidth(0.8);
      doc.line(36, pageH - 36, pageW - 36, pageH - 36);
      doc.setTextColor(120, 130, 140);
      doc.setFontSize(8);
      doc.text(opts.brand.name, 36, pageH - 22);
      doc.text(`Page ${i} / ${pages}`, pageW - 36, pageH - 22, {
        align: "right",
      });
    }
  };

  drawHeader();

  return {
    doc,
    startY: opts.meta.from ? 178 : 166,
    pageW,
    pageH,
    brandColor: BRAND_HEX,
    finish() {
      drawFooter();
      return Buffer.from(doc.output("arraybuffer"));
    },
    table(
      head: string[][],
      body: (string | number)[][],
      startY: number,
    ) {
      autoTable(doc, {
        startY,
        head,
        body,
        styles: {
          fontSize: 8,
          cellPadding: 4,
          overflow: "linebreak",
        },
        headStyles: {
          fillColor: [42, 90, 143],
          textColor: 255,
          fontStyle: "bold",
        },
        alternateRowStyles: { fillColor: [245, 248, 252] },
        margin: { left: 36, right: 36 },
      });
      return doc.lastAutoTable?.finalY || startY;
    },
  };
}
