export const ckb = {
  appName: "میدیا ئۆفیس",
  tagline: "ئەپی ئامادەبوونی کارمەندان",
  login: "چوونەژوورەوە",
  logout: "دەرچوون",
  email: "ئیمەیڵ",
  password: "وشەی نهێنی",
  home: "سەرەکی",
  history: "مێژوو",
  leave: "مۆڵەت",
  salary: "مووچە",
  notifications: "ئاگاداری",
  profile: "پرۆفایل",
  checkIn: "چک-ئین",
  checkOut: "چک-ئاوت",
  todayStatus: "دۆخی ئەمڕۆ",
  notCheckedIn: "هێشتا چک-ئینت نەکردووە",
  loading: "چاوەڕوان بە...",
  employeeOnly: "ئەم ئەپە تەنها بۆ کارمەندانە.",
  adminUseWeb: "بەڕێوەبەران پانێڵی وێب بەکاربهێنن.",
  comingSoon: "ئەم بەشە بەمزووانە چالاک دەبێت.",
  darkMode: "دۆخی تاریک",
  lightMode: "دۆخی ڕووناک",
  workingHours: "کاتژمێری کارکردن",
  gpsRequired: "GPS پێویستە بۆ ئامادەبوون",
} as const;
