export const ckb = {
  appName: "میدیا ئۆفیس",
  tagline: "سیستەمی زیرەڕێخستنی ئامادەبوونی کارمەندان",
  login: "چوونەژوورەوە",
  register: "دروستکردنی هەژماری کۆمپانیا",
  logout: "دەرچوون",
  email: "ئیمەیڵ",
  password: "وشەی نهێنی",
  fullName: "ناوی تەواو",
  companyName: "ناوی کۆمپانیا",
  phone: "ژمارەی مۆبایل",
  dashboard: "داشبۆرد",
  employees: "کارمەندان",
  departments: "بەشەکان",
  positions: "پۆستەکان",
  attendance: "ئامادەبوون",
  leave: "مۆڵەت",
  reports: "ڕاپۆرتەکان",
  notifications: "ئاگادارییەکان",
  qr: "کۆدی QR",
  activityLogs: "تۆماری چالاکی",
  backups: "پاشەکەوت",
  settings: "ڕێکخستنەکان",
  payroll: "مووچە و پاداشت",
  branches: "لقەکان",
  shifts: "شفتەکان",
  holidays: "پشووەکان",
  gpsHistory: "مێژووی GPS",
  print: "چاپکردن",
  desktopBlocked: "ئەپی کارمەند تەنها لە مۆبایل بەردەستە. تکایە لە مۆبایل بچۆ ژوورەوە.",
  checkIn: "چک-ئین",
  checkOut: "چک-ئاوت",
  salary: "مووچە",
  rewards: "پاداشت",
  profile: "پرۆفایل",
  history: "مێژوو",
  workplaceMap: "نەخشەی شوێنی کار",
  totalEmployees: "کۆی کارمەندان",
  present: "ئامادە",
  absent: "غائیب",
  late: "دواکەوتوو",
  overtime: "کاتی زیادە",
  recentActivity: "دوایین چالاکییەکان",
  search: "گەڕان...",
  save: "پاشەکەوتکردن",
  cancel: "هەڵوەشاندنەوە",
  add: "زیادکردن",
  edit: "دەستکاری",
  archive: "ئەرشیف",
  loading: "چاوەڕوان بە...",
  noData: "هیچ داتایەک نییە",
  darkMode: "دۆخی تاریک",
  lightMode: "دۆخی ڕووناک",
  welcomeBack: "بەخێربێیتەوە",
  createWorkspace: "دروستکردنی شوێنی کاری کۆمپانیا",
  alreadyHaveAccount: "هەژمارت هەیە؟",
  noAccount: "هەژمارت نییە؟",
  forgotPassword: "وشەی نهێنیت لەبیرچووە؟",
  resetPassword: "گۆڕینی وشەی نهێنی",
  registerHint: "هەژمارێکی نوێ تەنها بۆ کۆمپانیای خۆت دروست دەکات — داتای کۆمپانیای تر نابینرێت. دوای فۆرم، کۆدی ٦ ژمارەیی بۆ ئیمەیڵ دەنێردرێت.",
  employeeOnlyMobile: "کارمەندان تەنها لە ئەپی مۆبایل دەتوانن بچنە ژوورەوە.",
  accessDenied: "دەستگەیشتن ڕەتکرایەوە",
  adminOnly: "ئەم پانێڵە تەنها بۆ بەڕێوەبەرە.",
  comingSoon: "ئەم بەشە لە قۆناغی داهاتوودا تەواو دەبێت.",
} as const;

export type CkbKey = keyof typeof ckb;
